CREATE DATABASE SI;

CREATE TABLE SI.Person (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB;

CREATE TABLE SI.Image (
  id INTEGER NOT NULL AUTO_INCREMENT,
  tittle VARCHAR(200) NOT NULL,
  description TEXT NULL,
  photo VARCHAR(200) NOT NULL,
  comments TEXT NULL,
  PRIMARY KEY(id)
)ENGINE=INNODB;

CREATE TABLE SI.Users (
  id INTEGER NOT NULL AUTO_INCREMENT,
  idPerson INTEGER NOT NULL,
  nickName VARCHAR(50) NOT NULL,
  avatar VARCHAR(255) NULL,
  rol VARCHAR(100) NOT NULL,
  pass VARCHAR(255) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(idPerson)
    REFERENCES Person(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)ENGINE=INNODB;

CREATE TABLE SI.Album (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  idUsers INTEGER NOT NULL,
  description TEXT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(idUsers)
    REFERENCES Users(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)ENGINE=INNODB;

CREATE TABLE SI.ImagexAlbum (
  id INTEGER NOT NULL AUTO_INCREMENT,
  orderNumber INTEGER NOT NULL,
  idImage INTEGER NOT NULL,
  idAlbum INTEGER NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(idAlbum)
    REFERENCES Album(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idImage)
    REFERENCES Image(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)ENGINE=INNODB;
